spring:
  application:
    name: ingsis
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5437/test}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

server:
  port: ${API_PORT:8086}
  address: 0.0.0.0

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH0_ISSUER_URI}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH0_AUDIENCE}

redis:
  streams:
    testRequest: ${REDIS_STREAM_REQUEST_TEST_KEY}
    testResult: ${REDIS_STREAM_RESULT_TEST_KEY}
  groups:
    test: ${REDIS_GROUP_TEST_KEY}

bucket:
  url: ${BUCKET_URL}