name: Build & Push Test Image

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  call-cd-prod:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/cd-prod.yaml@main
    with:
      java-version: "21"
      environment: "development"
      service_name: "tester"
      image_route: "ghcr.io/ingsisprintscript/test-service:dev"
    secrets: inherit
